/**:
  ros__parameters:
    ############ system configuration ############
    # Data logging
    log_to_file: true
    log_debug: true
    log_enabled: [
        ## ADD LOGGER IDS HERE
        # tactic
        # "tactic",
        # "tactic.pipeline",
        # "tactic.module",
        # "tactic.module.live_mem_manager",
        # "tactic.module.graph_mem_manager",
        # path planner
        # "path_planning",
        # "path_planning.teb",
        # mission planner
        # "mission.server",
        # "mission.state_machine",
        # pose graph
        # "pose_graph",
        # pipeline specific
        "lidar.pipeline",
        # "lidar.honeycomb_converter",
        # "lidar.preprocessing",
        # "lidar.odometry_icp",
        # "lidar.odometry_map_maintenance",
        # "lidar.vertex_test",
        # "lidar.localization_map_recall",
        # "lidar.localization_icp",
        "lidar.intra_exp_merging",
        # "lidar.dynamic_detection",
        # "lidar.inter_exp_merging",
        # "lidar.change_detection",
        # "lidar.ground_extraction",
        # "lidar.obstacle_detection",
        # "lidar.terrain_assessment",
      ]

    ############ tactic configuration ############
    tactic:
      enable_parallelization: false
      preprocessing_skippable: false
      odometry_mapping_skippable: false
      localization_skippable: false

      task_queue_num_threads: 1
      task_queue_size: -1

      chain:
        min_cusp_distance: 1.5
        angle_weight: 7.0
        search_depth: 5
        search_back_depth: 10
        distance_warning: 5.0

      save_odometry_result: true
      save_localization_result: true
      visualize: true

      rviz_loc_path_offset: [0., 0., 0.]

    ############ pipeline configuration ############
    pipeline:
      type: lidar

      preprocessing: [
          # preprocessing thread modules
          "conversion",
          "filtering",
        ]

      odometry: [
          # odometry and mapping thread modules
          "icp",
          "mapping",
          "vertex_test",
          # "intra_exp_merging",
          # "dynamic_detection",
          # "inter_exp_merging",
          "memory",
        ]

      localization: [
          # localization thread modules
          "recall",
          "icp",
          # "change_detection",
          # "ground_extraction",
          # "obstacle_detection",
          "memory",
        ]

      # submap creation thresholds
      submap_translation_threshold: 1.5 # in meters
      submap_rotation_threshold: 30.0 # in degrees

    preprocessing:
      conversion:
        type: lidar.honeycomb_converter_v2

        visualize: true

      filtering:
        type: lidar.preprocessing

        num_threads: 6

        crop_range: 40.0

        frame_voxel_size: 0.1 # grid subsampling voxel size

        vertical_angle_res: 0.0132645 # vertical angle resolution in radius, equal to 0.76 degree documented in the manual
        polar_r_scale: 2.0 # polar_r_scale x vertical_angle_res = nearest neighbor search radius for normal computation
        r_scale: 4.0 # scale down point range by this value after taking log, whatever works
        h_scale: 1.54 # scale down yaw(phi) by this value so that vertical resolution ~= horizontal resolution, horizontal resolution when 5Hz spin frequence is ~1.17 degree, so 1.17 / 0.76 = 1.54

        num_sample1: 10000 # max number of sample after filtering based on planarity
        min_norm_score1: 0.95 # min planarity score

        num_sample2: 10000 # max number of sample after filtering based on planarity
        min_norm_score2: 0.2 # 0.2 is when the incident angle 5/12 * pi
        min_normal_estimate_dist: 1.0 # minimum distance to estimate normal in meters
        max_normal_estimate_angle: 0.44 # must <1/2, this value will be timed by M_PI

        cluster_num_sample: 10000 # maxnumber of sample after removing isolated points

        visualize: true

    odometry:
      icp:
        type: lidar.odometry_icp

        # motion prior terms
        trajectory_smoothing: true
        qc_diagonal: [1.0, 0.1, 0.1, 0.1, 0.1, 1.0]

        # ICP parameters
        num_threads: 6
        first_num_steps: 2
        initial_max_iter: 4
        initial_max_pairing_dist: 1.5
        initial_max_planar_dist: 1.0
        refined_max_iter: 50
        refined_max_pairing_dist: 1.0
        refined_max_planar_dist: 0.3
        averaging_num_steps: 2
        # steam parameters
        verbose: false
        max_iterations: 1

        # threshold
        min_matched_ratio: 0.5

        visualize: true

      mapping:
        type: lidar.odometry_map_maintenance

        map_voxel_size: 0.1
        crop_range_front: 40.0
        back_over_front_ratio: 0.5

        point_life_time: 20.0

        visualize: true

      vertex_test:
        type: lidar.vertex_test

        max_translation: 0.5
        max_rotation: 10.0

      intra_exp_merging:
        type: "lidar.intra_exp_merging_v2"

        depth: 6.0

        map_voxel_size: 0.1
        crop_range_front: 40.0
        back_over_front_ratio: 0.5

        visualize: true

      dynamic_detection:
        type: "lidar.dynamic_detection"
        depth: 2

        horizontal_resolution: 0.02042
        vertical_resolution: 0.01326
        max_num_observations: 2000
        min_num_observations: 4
        dynamic_threshold: 0.3

        visualize: true

      inter_exp_merging:
        type: "lidar.inter_exp_merging"
        depth: 2

        horizontal_resolution: 0.02042
        vertical_resolution: 0.01326
        max_num_observations: 2000
        min_num_observations: 4
        dynamic_threshold: 0.3

        max_num_experiences: 128

        visualize: true

      memory:
        type: "live_mem_manager"

        window_size: 5

    localization:
      recall:
        type: lidar.localization_map_recall

        map_version: "pointmap"

        visualize: true

      icp:
        type: lidar.localization_icp

        use_pose_prior: true

        # ICP parameters
        num_threads: 6
        first_num_steps: 2
        initial_max_iter: 4
        initial_max_pairing_dist: 1.5
        initial_max_planar_dist: 1.0
        refined_max_iter: 50
        refined_max_pairing_dist: 1.0
        refined_max_planar_dist: 0.3
        averaging_num_steps: 2

        # steam parameters
        verbose: false
        max_iterations: 1

        # threshold
        min_matched_ratio: 0.3

      memory:
        type: "graph_mem_manager"

        vertex_life_span: 5
        window_size: 3

      change_detection:
        type: "lidar.change_detection_v2"
        # change detection
        search_radius: 0.25
        # cost map
        resolution: 0.5
        size_x: 16.0
        size_y: 8.0
        # general
        run_online: false
        run_async: true
        visualize: true
        save_module_result: true

      obstacle_detection:
        type: "lidar.obstacle_detection"

        z_min: 0.5
        z_max: 2.0

        resolution: 0.6
        size_x: 40.0
        size_y: 20.0

        run_async: true
        visualize: true

      ground_extraction:
        type: "lidar.ground_extraction"

        z_offset: 0.2

        alpha: 0.035 # 2.0 * M_PI / 180.0
        tolerance: 0.25
        Tm: 0.3
        Tm_small: 0.1
        Tb: 0.5
        Trmse: 0.1
        Tdprev: 1.0

        rmin: 2.0
        num_bins_small: 30
        bin_size_small: 0.5
        num_bins_large: 10
        bin_size_large: 1.0

        resolution: 0.6
        size_x: 40.0
        size_y: 20.0

        run_async: true
        visualize: true

      terrain_assessment:
        type: "lidar.terrain_assessment"
        # corridor computation
        lookahead_distance: 15.0
        corridor_width: 1.0
        # terrain assessment
        search_radius: 1.0
        # cost map
        resolution: 0.5
        size_x: 40.0
        size_y: 20.0
        # general
        run_online: false
        run_async: true
        visualize: true

    ############ tactic configuration ############
    path_planning:
      type: teb
      control_period: 100 # ms
      teb:
        # vtr specific
        visualize: true
        extrapolate: true
        extrapolation_timeout: 2.0
        lookahead_distance: 8.0
        # robot specific
        robot_model: circular
        robot_radius: 0.5
        # teb specific
        map_frame: "planning frame"
        enable_homotopy_class_planning: true

        free_goal_vel: true
        max_vel_x: 0.6
        max_vel_y: 0.0
        max_vel_theta: 0.3
        min_turning_radius: 3.0
        weight_viapoint: 0.5
        weight_costmap: 1000.0
