/**:
  ros__parameters:
    log_to_file: true
    log_debug: true
    log_enabled:
        # navigator
      - navigation
      #- navigation.graph_map_server
      #- navigation.command
    
        # tactic
      #- tactic
      #- tactic.pipeline
      - tactic.module
      #- tactic.module.live_mem_manager
      #- tactic.module.graph_mem_manager

        # path planner
      #- path_planning
      #- path_planning.cbit
      #- path_planning.cbit_planner
      #- obstacle detection.cbit
      #- grizzly_controller_tests.cbit
      - ouster
      - test
        
        # mission planner
      #- mission.server
      #- mission.state_machine

        # pose graph
      #- pose_graph

        # lidar pipeline
      #- lidar.pipeline
      #- lidar.preprocessing
      #- lidar.ouster_converter
      #- lidar.odometry_icp
      #- lidar.odometry_map_maintenance
      - lidar.vertex_test
      #- lidar.localization_map_recall
      #- lidar.localization_icp
      #- lidar.intra_exp_merging

    robot_frame: base_link
    env_info_topic: env_info
    lidar_frame: os_lidar
    lidar_topic: /ouster/points
    queue_size: 1
    graph_map:
      origin_lat: 43.7822
      origin_lng: -79.4661
      origin_theta: 1.3
      scale: 1.0
    tactic:
      enable_parallelization: true
      preprocessing_skippable: false
      odometry_mapping_skippable: false
      localization_skippable: true
      task_queue_num_threads: 1
      task_queue_size: -1

      route_completion_translation_threshold: 0.5

      chain:
        min_cusp_distance: 1.5
        angle_weight: 7.0
        search_depth: 5
        search_back_depth: 10
        distance_warning: 5.0
      save_odometry_result: true
      save_localization_result: true
      visualize: true
      rviz_loc_path_offset:
        - 0.0
        - 0.0
        - 0.0
    pipeline:
      type: lidar
      submap_translation_threshold: 1.5
      submap_rotation_threshold: 10.0
      save_raw_point_cloud: true
    localization:
      change_detection_sync:
        type: lidar.change_detection_v3
        detection_range: 30.0
        search_radius: 0.25

        negprob_threshold: 0.75 # was 0.015 # -1.86 without prior, 0.015 with prior # Jordy: I found I needed to bump this up abit (approx 0.075+) to reduce false positives
        use_prior: true
        alpha0: 3.0
        beta0: 0.03
        use_support_filtering: true
        support_radius: 0.25
        support_variance: 0.05
        support_threshold: 2.5
        visualize: true

      save_nearest:
        type: lidar.cd_testing
        suffix: nearest
      memory:
        type: graph_mem_manager
        vertex_life_span: 5
        window_size: 3
      lasersam:
        type: lidar.SAM
        use_gpu: true
        abs_filepath: false
        filepath: sam_vit_b_fast_cuda.torchscript
        img_width: 256
        img_height: 128
        h_fov: 1.5707
        v_fov: 0.7853
        min_range: 0.5
        max_range: 30.0
        num_prompts: 5
        corridor_width: 100.0
        smooth_size: 40
        iou_threshold: 0.75
        max_size: 0.1
        visualize: true
      save_lasersam:
        type: lidar.cd_testing
        suffix: lasersam
      range_change:
        type: torch.range_change
        use_gpu: true
        abs_filepath: false
        filepath: exported_model_flat_10m.pt
        radius_filter: 0.25
        neighbourhood: 5
        save_nn_point_cloud: false
        range_crop: 30.0
      save_range_change:
        type: lidar.cd_testing
        suffix: rangenetcd
      pixel_diff:
        type: lidar.cd_pixel_diff
        threshold: 210

    
    path_planning:
      type: stationary